### ISSUE TITLE
With XboxLive?

### ISSUE THREAD

**Issue by SuperAdam47** [CTMCentral/Friends#1]

**Comment by provsalt** [comment]
![image](https://user-images.githubusercontent.com/39023494/83406870-21cb7480-a442-11ea-82b9-36e0f6cd6bc8.png)

**Comment by SuperAdam47** [comment]
Friends in xbox live :)

**Comment by provsalt** [comment]
Do we look like microsoft who can access your friends list?

**Comment by jasonw4331** [comment]
If big servers like lifeboat can't do it, then don't expect us to be able to
